- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    
    - name: update the server
      apt:
        update_cache: true
      changed_when: False
  tasks:
    - include_tasks: tasks/packages.yml


